"""Add url field to NewsArticle

Revision ID: 4033f0ae1e4a
Revises: a84a3fc8d52a
Create Date: 2024-12-24 00:59:32.662219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4033f0ae1e4a'
down_revision = 'a84a3fc8d52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
