"""empty message

Revision ID: 5266b2350fd5
Revises: 4bcc4c39e58e
Create Date: 2024-12-30 16:01:31.599910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5266b2350fd5'
down_revision = '4bcc4c39e58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_analysis_article_id'), ['article_id'], unique=False)

    op.create_table('sentiment_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_analysis_article_id'), ['article_id'], unique=False)

    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_article_id'))

    op.drop_table('summary')
    with op.batch_alter_table('sentiment_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_analysis_article_id'))

    op.drop_table('sentiment_analysis')
    with op.batch_alter_table('keyword_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_analysis_article_id'))

    op.drop_table('keyword_analysis')
    # ### end Alembic commands ###
